plugins {
    id 'multiloader-loader'
    id 'net.fabricmc.fabric-loom'

    id "com.modrinth.minotaur" version "2.+"
    id "io.github.CDAGaming.cursegradle" version "1.6.1"
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"

    implementation "fuzs.forgeconfigapiport:forgeconfigapiport-fabric:26.1.0.2"
}

loom {
    def aw = project(':common').file("src/main/resources/${mod_id}.accesswidener")
    if (aw.exists()) {
        accessWidenerPath.set(aw)
    }
    runs {
        client {
            client()
            setConfigName('Fabric Client')
            ideConfigGenerated(true)
            runDir('runs/client')
        }
        server {
            server()
            setConfigName('Fabric Server')
            ideConfigGenerated(true)
            runDir('runs/server')
        }
    }
}

// Implement mcgradleconventions loader attribute
def loaderAttribute = Attribute.of('io.github.mcgradleconventions.loader', String)
['apiElements', 'runtimeElements', 'includeInternal', 'modCompileClasspath'].each { variant ->
    configurations.named("$variant") {
        attributes {
            attribute(loaderAttribute, 'fabric')
        }
    }
}
sourceSets.configureEach {
    [it.compileClasspathConfigurationName, it.runtimeClasspathConfigurationName].each { variant->
        configurations.named("$variant") {
            attributes {
                attribute(loaderAttribute, 'fabric')
            }
        }
    }
}

modrinth {
    token = System.getenv("MODRINTH_TOKEN")
    projectId = "bI9lnAFH" // Required, must be a string, ID of Modrinth project
    versionName = "${mod_name} (Fabric) - v${version} - ${minecraft_version}"
    versionType = "release"
    uploadFile = jar
    gameVersions = ["26.1"]
    loaders = ["fabric"]
    changelog = rootProject.file("CHANGELOG.md").text

    dependencies {
        required.project "fabric-api"
        optional.project "forge-config-api-port"
    }
}

curseforge {
    project {
        apiKey = System.getenv("CURSEFORGE_TOKEN")

        id = "908384"
        releaseType = "release"


        changelog = rootProject.file("CHANGELOG.md").text
        changelogType = "markdown"
        gameVersionStrings = ["26.1", "Fabric"]
        mainArtifact(jar) {
            it.displayName = "${mod_name} (Fabric) - v${version} - ${minecraft_version}"

            relations {
                it.requiredDependency "fabric-api"
                it.requiredDependency "forge-config-api-port"
            }
        }
    }
}
